blank_issues_enabled: false
contact_links:
  - name: Security issue
    url: https://github.com/iampopovich/GOG-Countries/security/advisories/new
    about: Please report vulnerabilities via private security advisory.
